### PR TITLE
1 phase commit

### PR DESCRIPTION
**Pull request by cjy9306**
Baekjoon algorithm 1 phase commit

### CODE REVIEW

**Review by kor-haru — CHANGES_REQUESTED** [review]
Keep the source code consistent plz. especially open the curly brackets

**Review by kor-haru — DISMISSED** [review]

**Review by kor-haru — APPROVED** [review]
Thx to update

**Review by jukqaz — APPROVED** [review]
👍

**Comment by cjy9306** [comment]
👍

**Review by korJiusngPark — APPROVED** [review]
AGG

**Review by AlvinYou — APPROVED** [review]

**Review by AlvinYou — APPROVED** [review]
👍

**Pull request merged**
