### PR TITLE
yys/step2

### PR DESCRIPTION
**Pull request by AlvinYou**

### CODE REVIEW

**Review by cjy9306 — DISMISSED** [review]
all

**Review by kor-haru — CHANGES_REQUESTED** [review]
Keep the source code consistent plz. especially semicolon

**Review by jukqaz — CHANGES_REQUESTED** [review]
@AlvinYou 
Why did you include the first step?
I think you exclude first step.

**Comment by AlvinYou** [comment]
clear step1 files.
@dopingcat cleared semicolons of all files. plz PR approach.

**Pull request closed without merging**
